Hotel/hotelstar/hotel/urls.py
from django.urls import path
from . import views

app_name = 'hotel'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('about', views.about, name='about'),
    path('services', views.services, name='services'),
    path('testimonials', views.testimonials, name='testimonials'),
    path('contact', views.contact, name='contact'),
    path('test', views.test, name='test'),
    path('singletest/<int:id>', views.single_test, name='singletest'),
    path('seemore/<int:id>', views.see_more, name='seemore'),
]

Hotel/hotelstar/hotel/models.py
from django.db import models

# Create your models here.
class Hotel(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField()
    stars = models.IntegerField()
    price = models.IntegerField()
    picture = models.ImageField(upload_to='images', default="images/124180566_3771168516249284_3976912378791517206_o.jpg")
    HOTEL_TYPE = (
        ("1", "Free WiFi"),
        ("2", "No WiFi"),
    )
    HOTEL_TYPE2 = (
        ("1", "Free Parking"),
        ("2", "No Parking")
    )

    hotel_type = models.CharField(max_length=128, default="1", choices=HOTEL_TYPE)
    hotel_type2 = models.CharField(max_length=128, default=1, choices=HOTEL_TYPE2)



    def __str__(self):
        return self.name + " | " + str(self.stars) + " Stars"

    class Meta:

        verbose_name_plural = 'Hotels'



class HotelReview(models.Model):
    review = models.ForeignKey(Hotel, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=128, null=True)
    email = models.EmailField(max_length=128, null=True)
    comment = models.TextField(max_length=1000, null=True)
    RATING_NUMBER = (
        ("1", "1"),
        ("2", "2"),
        ("3", "3"),
        ("4", "4"),
        ("5", "5"),

    )

    rating_number = models.CharField(max_length=128, default="5", choices=RATING_NUMBER, null=True)
    picture = models.ImageField(upload_to='images', default="images/saakadze.jpg", null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    permission = models.BooleanField(default=True)

    def __str__(self):
        return str(self.name)

    class Meta:

        verbose_name_plural = 'Reviews'
        ordering = ['-created_on']



class Contact(models.Model):
    name = models.CharField(max_length=128)
    email = models.EmailField(max_length=128)
    message = models.TextField(max_length=1000)

    def __str__(self):
        return self.name

    class Meta:

        verbose_name_plural = 'Contacts'


class Test(models.Model):
    name = models.CharField(max_length=128)
    gender = models.CharField(max_length=128)

Hotel/hotelstar/hotel/forms.py
from django import forms
from .models import Test, HotelReview, Contact

class TestForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = ('name', 'gender')

class HotelReviewForm(forms.ModelForm):
    class Meta:
        model = HotelReview
        fields = ('name', 'email', 'comment', 'rating_number')
        # exclude ანუ რასაც შიგნით შევიტანტ იმის გარდა გამოიტანოს ყველაფერი.
        # widgets = {
        #     'name': forms.TextInput(attrs={'class': 'form-control'}),
        #     'email': forms.TextInput(attrs={'class': 'form-control'}),
        #     'comment': forms.Textarea(attrs={'class': 'form-control'}),
        #     'rating_number': forms.Select(attrs={'class': 'form-control'})
        # }


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'message')

Hotel/hotelstar/hotel/views.py
from django.shortcuts import render, redirect
from . models import Hotel, Contact, HotelReview
from .forms import TestForm, HotelReviewForm, ContactForm


# Create your views here.

def homepage(request):
    hotels = Hotel.objects.all()
    reviews = HotelReview.objects.all()
    good_hotels = ()
    for i in hotels:
        if i.stars == 5 and len(good_hotels) < 3:
            good_hotels += (i,)

    context = {
        'good_hotels' : good_hotels,
        'hotels' : hotels,
    }

    return render(request, 'hotel/index.html', context)

def about(request):
    hotels = Hotel.objects.all()
    hotel = Hotel.objects.get(id=1)
    rame = Hotel.objects.filter(stars=2)
    return render(request, 'hotel/about.html')

def services(request):
    return render(request, 'hotel/services.html')

def testimonials(request):
    return render(request, 'hotel/testimonials.html')

def contact(request, id):
    contact = Contact.objects.get(id=id)
    form = ContactForm()
    if request.method == "GET":
        form = ContactForm(request.GET or None)   #request.FILES მედიას ატვირთვა თუ გვინდა
        if form.is_valid():
            data = form.save(commit=False)
            data.review = contact
            data.name = form.cleaned_data.get("name")
            data.email = form.cleaned_data.get('email')
            data.message = form.cleaned_data.get('message')
            data.permission = True
            data.save()

            return redirect('hotel:contact', id)

    context = {
        'contact':contact,
        'form':form,

    }
    return render(request, 'hotel/seemore.html', context)

def test(request):
    hotels = Hotel.objects.all()
    hotels_star = request.GET.get('stars')
    hotels_description = request.GET.get('description')
    hotels_name = request.GET.get('name')

    bad_hotels = ()
    shit_hotels = ()

    if hotels_name != '' and hotels_name is not None:
        hotels = hotels.filter(name__contains=hotels_name)
    elif hotels_description != '' and hotels_description is not None:
        hotels = hotels.filter(description__contains=hotels_description)
    elif hotels_star != '' and hotels_star is not None:
        hotels = hotels.filter(stars__gte=hotels_star)

    for i in hotels:
        if i.hotel_type == "1":
            bad_hotels += (i,)

            print(bad_hotels)
        else:
            shit_hotels += (i,)

            print(shit_hotels)


    print(bad_hotels)
    context = {
        'hotels' : hotels,
        'bad_hotels' : bad_hotels,
        'shit_hotels' : shit_hotels,
    }
    return render(request, 'hotel/test.html', context)


def single_test(request, id):
    contact = Contact.objects.get(id=id)
    form = TestForm()
    if request.method == "GET":
        form = TestForm(request.GET)
        if form.is_valid():
            data = form.save(commit=False)
            data.permission = True
            data.save()

            return redirect('hotel:singletest', id)


    context = {
        'contact':contact,
        'form':form,

    }
    return render(request, 'hotel/single_test.html', context)

def see_more(request, id):
    seemore = Hotel.objects.get(id=id)
    reviews = HotelReview.objects.filter(review=id, permission=True)[:2]

    form = HotelReviewForm()
    if request.method == "GET":
        form = HotelReviewForm(request.GET or None)   #request.FILES მედიას ატვირთვა თუ გვინდა
        if form.is_valid():
            data = form.save(commit=False)
            data.review = seemore
            data.name = form.cleaned_data.get("name")
            data.email = form.cleaned_data.get('email')
            data.comment = form.cleaned_data.get('comment')
            data.rating_number = form.cleaned_data.get('rating_number')
            data.permission = True
            data.save()

            return redirect('hotel:seemore', id)

    context = {
        'seemore':seemore,
        'reviews':reviews,
        'form':form,
    }
    return render(request, 'hotel/seemore.html', context)

Hotel/hotelstar/hotel/templates/hotel/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Parallo - App Landing Page</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" />
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/templatemo-style.css' %}" />
    <link rel="stylesheet" href="{% static 'js/bootstrap.min.js' %}" />
    <link rel="stylesheet" href="{% static 'jquery.min.js' %}" />
    <link rel="stylesheet" href="{% static 'parallax.min.js' %}" />
<!--
Parallo Template
https://templatemo.com/tm-534-parallo
-->
  </head>
  <body>
    <div class="parallax-window" data-parallax="scroll" data-image-src="{% static 'img/bg-01.jpg' %}">
      <div class="container-fluid">
        <div class="row tm-brand-row">
          <div class="col-lg-4 col-11">
            <div class="tm-brand-container tm-bg-white-transparent">
              <i class="fas fa-2x fa-pen tm-brand-icon"></i>
              <div class="tm-brand-texts">
                <h1 class="text-uppercase tm-brand-name">Parallo</h1>
                <p class="small">new app landing page</p>
              </div>
            </div>
          </div>
          <div class="col-lg-8 col-1">
            <div class="tm-nav">
              <nav class="navbar navbar-expand-lg navbar-light tm-bg-white-transparent tm-navbar">
                <button class="navbar-toggler" type="button"
                  data-toggle="collapse" data-target="#navbarNav"
                  aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav">
                    <li class="nav-item">
                      <div class="tm-nav-link-highlight"></div>
                      <a class="nav-link" href="{% url 'hotel:homepage' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                      <div class="tm-nav-link-highlight"></div>
                      <a class="nav-link" href="{% url 'hotel:about' %}">About</a>
                    </li>
                    <li class="nav-item">
                      <div class="tm-nav-link-highlight"></div>
                      <a class="nav-link" href="{% url 'hotel:services' %}">Services</a>
                    </li>
                    <li class="nav-item">
                      <div class="tm-nav-link-highlight"></div>
                      <a class="nav-link" href="{% url 'hotel:testimonials' %}">Testimonials</a>
                    </li>
                    <li class="nav-item">
                      <div class="tm-nav-link-highlight"></div>
                      <a class="nav-link" href="{% url 'hotel:contact' %}">Contact</a>
                    </li>
                  </ul>
                </div>
              </nav>
            </div>
          </div>
        </div>
        <a href="/login" ><b class="tm-slogan text-white">Log In</b><a/>
        <b class="tm-slogan text-white">|</b>
        <a href="/signup" ><b class="tm-slogan text-white">Register</b><a/>


        {% block content %}

        {% endblock %}

          <!-- Page footer -->
        <footer class="row">
          <p class="col-12 text-white text-center tm-copyright-text">
            Copyright &copy; 2020 App Landing Page.
            Designed by <a href="#" class="tm-copyright-link">TemplateMo</a>
          </p>
        </footer>
      </div>
      <!-- .container-fluid -->
    </div>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/parallax.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

Hotel/hotelstar/hotel/templates/hotel/seemore.html
{% extends 'hotel/base.html' %}
{% block content %}
{% load static %}

        <!-- Hotel -->
        <section>
            <div class="title5">
                <div class="titleplacement">
                    <p class="titletext">{{ seemore.name }}</p>
                </div>
            </div>
            <img src="{% static 'img/ambassadori.jpg' %}" class="cover" alt="tinki">
            <div class="hoteldesc">
                <p class="titletext">Hotel Description:</p>
                <p class="desctext">
                    {{ seemore.description }}                </p>
            </div>
            <div class="roomContainer">
                <div class="roomImgContainer">
                    <p class="paddingForTtl">Luxury Suit - $220</p>
                    <img src="{% static 'img/luxurySuit.jpg' %}" alt="Luxury Suit Image" class="roomPictures">
                    <form class="paddingForBtn">
                      <a href="seemore.html"> <input class="see-more" type="button" value="Book"></a>
                    </form>
                </div>
                <div class="roomImgContainer">
                    <p class="paddingForTtl">Junior Suit - $180</p>
                    <img src="{% static 'img/juniorSuit.jpg' %}" alt="Luxury Suit Image" class="roomPictures">
                    <form class="paddingForBtn">
                      <a href="seemore.html"> <input class="see-more" type="button" value="Book"></a>
                    </form>
                </div>
                <div class="roomImgContainer">
                    <p class="paddingForTtl">Superior Twin - $150</p>
                    <img src="{% static 'img/superiorTwin.jpg' %}" alt="Luxury Suit Image" class="roomPictures">
                    <form class="paddingForBtn">
                      <a href="seemore.html"> <input class="see-more" type="button" value="Book"></a>
                    </form>
                </div>
            </div>
            <div class="facilities-reviews">
                <div class="facilities">
                   <p class="se-p">Popular Facilities</p>
                   <ul>
                       <li class="fac"><i class="fas fa-swimmer iconsize"></i>   2 Swimming Pools</li>
                       <li class="fac"><i class="fas fa-wifi iconsize"></i>   Free WiFi</li>
                       <li class="fac"><i class="fas fa-parking iconsize"></i>   Free Parking</li>
                       <li class="fac"><i class="fas fa-utensils iconsize"></i>   Free Breakfast</li>
                       <li class="fac"><i class="fas fa-shuttle-van iconsize"></i>   Airport Shuttle</li>
                       <li class="fac"><i class="fas fa-child iconsize"></i>   Family Rooms</li>
                       <li class="fac"><i class="fas fa-spa iconsize"></i>   Spa</li>
                       <li class="fac"><i class="fas fa-glass-martini-alt iconsize"></i>  Bar</li>
                   </ul>
                </div>
                <div class="reviews">
                    <div class="reviewBox1">
                        <h1 class="se-review">Reviews:</h1>
                        {% for review in reviews %}
                        <div class="reviewBox1Child">
                            <div class="nameHolder">
                                <img src="{{ review.picture.url }}" class="customerPic" alt="Customer Picture">
                                <p class="customerName">{{ review.name }}</p>
                                <div class="reviewStars">
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                                </div>
                                <p class="reviewRating">{{ review.rating_number }}</p>
                            </div>
                            <div class="reviewText">
                                <p>{{ review.comment }}</p>
                            </div>
                        </div>
                        {% endfor %}
                        <form class="allReviewsButton">
                            <a href="#">
                                <input class="rating-submitter" type="button" value="All reviews">
                            </a>
                        </form>
                    </div>
                    <div class="reviewBox2">
                        <form method="GET" action="{% url 'hotel:seemore' seemore.id %}">
                        <p class="review-title">Write a Review:</p>
                            <div class="reviewBox2child">
                                <label>Name</label>
                                <input type="text" name="name" class="name-email-input">
                            </div>
                            <div class="reviewBox2child">
                                <label>Email</label>
                                <input type="text" name="email" class="name-email-input">
                            </div>
                            <div class="reviewBox2child">
                                <label>Comment</label>
                                <textarea type="text" name="comment" class="comment-input"></textarea>
                            </div>
                            <div class="reviewBox2child">
                                <label>Rate Our Service</label>
                                  <select name="rating_number" id="hotel rating" class="rating-selector">
                                    <option value="1">  1 Star</option>
                                    <option value="2">  2 Star</option>
                                    <option value="3">3 Star</option>
                                    <option value="4"> 4 Star</option>
                                    <option value="5"> 5 Star</option>
                                  </select>
                            </div>
                            <div class="rating-button-holder">
                               <input type="submit" class="rating-submitter">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>

        {% endblock %}

Hotel/hotelstar/hotel/templates/hotel/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


                <form method="GET" action="{% url 'hotel:test' %}">
                        <input type="text" name="name">
                    <input type="text" name="description">
                    <input type="text" name="stars">


                        <input type="submit">
                    </form>


    {% for hotel in bad_hotels %}
    <div>
        <h1><a href="{% url 'hotel:singletest' hotel.id %}">{{ hotel.name }}</a></h1>
        <h1>{{ hotel.get_hotel_type_display }}</h1>
        <p>description: {{ hotel.description }}</p>
    </div>
    {% endfor %}


---------------------------------------------------------
    {% for hotel in shit_hotels %}
    <div>
        <h1><a href="{% url 'hotel:singletest' hotel.id %}">{{ hotel.name }}</a></h1>
        <h1>{{ hotel.get_hotel_type_display }}</h1>
        <p>description: {{ hotel.description }}</p>
    </div>
    {% endfor %}


</body>
</html>